services:
  database:
    ports:
      - 5432:5432
    container_name: postgresql
    image: postgres
    environment:
      - POSTGRES_DB=spring_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=VstII8;j7:xADFmGf8e5o9DnThcntX

  backend:
    build: ./
    container_name: auth-spring-boot-app
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://database:5432/spring_auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=VstII8;j7:xADFmGf8e5o9DnThcntX
    depends_on:
      - database
