spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/spring_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:toor}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
