spring:
  datasource:
    url: jdbc:postgresql://database:5432/spring_auth
    username: postgres
    password: VstII8;j7:xA"DFmGf8e5o9DnT"hcntX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
